### ISSUE TITLE
An exception occur in "T220 DataEntryAndSetupForms_2022R1 -> Step 1.2.1: Creating a Work Order from a Template (with RowUpdated) -> Testing the Logic"

### ISSUE THREAD

**Issue by mehmetyagci** [Acumatica/Help-and-Training-Examples#76]
I tried to rewrite the T220 codes.
I got the following exception in "Testing the Logic" part of the doc.
`PX.Data.PXException: 'Error: An error occurred during processing of the field LineNbr: Object reference not set to an instance of an object..'`

The details are as follows:
```

PX.Data.PXException
  HResult=0x80131500
  Message=Error: An error occurred during processing of the field LineNbr: Object reference not set to an instance of an object..
  Source=PX.Data
  StackTrace:
   at PX.Data.PXCache`1.FillWithValues(TNode copy, TNode& item)
   at PX.Data.PXCache`1.Insert(Object data, Boolean bypassinterceptor)
   at PX.Data.PXCache`1.Insert(Object data)
   at PX.Data.PXCache`1.Insert()
   at PX.Data.PXSelectBase`1.Insert()
   at PhoneRepairShop.RSSVWorkOrderEntry._(RowUpdated`1 e) in D:\Acumatica ERP\IIS\2022R2\App_Data\Projects\PhoneRepairShop\PhoneRepairShop_Code\RSSVWorkOrderEntry.cs:line 46
   at PX.Data.Events.Event`2.Adapter.Execute(PXCache c, EventArgs a)
   at PX.Data.PXCache.OnRowUpdated(Object newItem, Object oldItem, Boolean externalCall)
   at PX.Data.PXCache`1.Update(IDictionary keys, IDictionary values)
   at PX.Data.PXGraph.ExecuteUpdate(String viewName, IDictionary keys, IDictionary values, Object[] parameters)

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
NullReferenceException: Object reference not set to an instance of an object.
```
The exception details screenshot is as follows:
![image](https://user-images.githubusercontent.com/2571175/202923405-f58efd4a-4fd9-42d6-bbc3-cd3aa6792dd9.png)

And, my local Acumatica version is as follows:
Acumatica 2021 R2
Build 21.207.0045 Customization: PhoneRepairShop

**Comment by k-s-popova** [comment]
Hi @mehmetyagci, please check the attributes you assigned to RSSVWorkOrder.RepairItemLineCntr and RSSVWorkOrderItem.LineNbr. If you have any issues related to the course, please write to training@acumatica.com.
